import "./globals.css";
import { Providers } from "./providers";
import Link from "next/link";

import "primereact/resources/themes/lara-dark-teal/theme.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import { Card } from "primereact/card";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Card className="m-6 ">{children}</Card>
        </Providers>
      </body>
    </html>
  );
}
